name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install pipenv
        run: pip install pipenv

      - name: Install deps
        run: pipenv install
        
      - name: Deploy Bot
        run: pipenv run python myBot.py
