name: Export Database and Deploy Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy Bot
        run: python myBot.py

      - name: Export Database to CSV
        run: python export_to_csv.py
